require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/book_entries", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BookEntry. As you add validations to BookEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BookEntry.create! valid_attributes
      get book_entries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      book_entry = BookEntry.create! valid_attributes
      get book_entry_url(book_entry)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_book_entry_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      book_entry = BookEntry.create! valid_attributes
      get edit_book_entry_url(book_entry)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BookEntry" do
        expect {
          post book_entries_url, params: { book_entry: valid_attributes }
        }.to change(BookEntry, :count).by(1)
      end

      it "redirects to the created book_entry" do
        post book_entries_url, params: { book_entry: valid_attributes }
        expect(response).to redirect_to(book_entry_url(BookEntry.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BookEntry" do
        expect {
          post book_entries_url, params: { book_entry: invalid_attributes }
        }.to change(BookEntry, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post book_entries_url, params: { book_entry: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested book_entry" do
        book_entry = BookEntry.create! valid_attributes
        patch book_entry_url(book_entry), params: { book_entry: new_attributes }
        book_entry.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the book_entry" do
        book_entry = BookEntry.create! valid_attributes
        patch book_entry_url(book_entry), params: { book_entry: new_attributes }
        book_entry.reload
        expect(response).to redirect_to(book_entry_url(book_entry))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        book_entry = BookEntry.create! valid_attributes
        patch book_entry_url(book_entry), params: { book_entry: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested book_entry" do
      book_entry = BookEntry.create! valid_attributes
      expect {
        delete book_entry_url(book_entry)
      }.to change(BookEntry, :count).by(-1)
    end

    it "redirects to the book_entries list" do
      book_entry = BookEntry.create! valid_attributes
      delete book_entry_url(book_entry)
      expect(response).to redirect_to(book_entries_url)
    end
  end
end
